name: "Build"

on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Build"
      run: cd build; TERM=dumb ./build.sh
    - name: "Create artifact"
      run: |
         zip r2recompress-${{github.ref_name}}.zip r2recompress.exe
    - uses: softprops/action-gh-release@v1
      with:
        files: r2recompress-${{github.ref_name}}.zip
